spring:
  datasource:
    # Dentro de Docker, NO uses localhost. Usa el nombre del servicio.
    url: jdbc:mysql://descuentos-mysql:3306/db_descuentos 
    username: root
    password: root
  jpa:
    hibernate:
      # Esto evita que Hibernate intente modificar la tabla y falle por las fechas
      ddl-auto: none 
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          # También cambiamos localhost por el nombre del contenedor de Keycloak
          issuer-uri: http://keycloak-sso:9090/realms/videoclub

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
